### ISSUE TITLE
Nextjs Errors

### ISSUE THREAD

**Issue by chuckstock** [wevm/frog-archived#14] opened 2024-02-28 20:41 UTC
Getting serveral issues with nextjs

running create from docs `bunx create-frog -t next` results in:
```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1097:7)
    at getTemplates (file:///private/tmp/bunx-501-create-frog@latest/node_modules/create-frog/_lib/utils/getTemplates.js:4:27)
    at file:///private/tmp/bunx-501-create-frog@latest/node_modules/create-frog/_lib/bin.js:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

then when i do a manual install and just copy the exact docs from nextjs page i get this error
```
TypeError: Cannot read properties of undefined (reading '__type')
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/utils/parseIntents.js:34:22)
    at parseIntent (webpack-internal:///(rsc)/./node_modules/frog/_lib/utils/parseIntents.js:45:7)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/utils/parseIntents.js:16:57)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/utils/parseIntents.js:16:48)
    at parseIntents (webpack-internal:///(rsc)/./node_modules/frog/_lib/utils/parseIntents.js:21:7)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/frog-base.js:208:177)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:34:27)
    at async eval (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:246:33)
    at async /Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809
    at async eU.execute (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1543:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1463:28)
    at async DevServer.renderPageComponent (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1856:24)
    at async DevServer.renderToResponseImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1894:32)
    at async DevServer.pipeImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/next-server.js:271:17)
    at async DevServer.handleRequestImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:807:17)
    at async /Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/router-server.js:163:21)
    at async handleRequest (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/router-server.js:342:24)
    at async requestHandlerImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/router-server.js:366:13)
    at async Server.requestListener (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/start-server.js:140:13)
    ```

**Comment by jxom** [comment] 2024-02-28 21:02
For first error, what version of Bun are you on? I can't reproduce here.

For second, add `/** @jsxImportSource frog/jsx */` to the top of the TSX file. Will add to docs.

UPDATE: added

**Comment by chuckstock** [comment] 2024-02-28 21:12
bun version v1.0.29

**Comment by chuckstock** [comment] 2024-02-28 21:15
awesome adding the comment fixed that issue.

now i'm running that basic frame in frog dev frame and getting this error whenever i click on any buttons:
```
SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/dev/routes.js:160:40)
    at dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:34:33)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:11:16)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:246:39)
    at _Hono.dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:254:11)
    at _Hono.fetch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:68:25)
    at _Hono.eval (webpack-internal:///(rsc)/./node_modules/hono/dist/adapter/vercel/handler.js:7:20)
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63815
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56866
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:37102)
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54639
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:36351)
    at /Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54601
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at eU.execute (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53994)
    at eU.handle (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65073)
    at doRender (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1333:60)
    at cacheEntry.responseCache.get.routeKind (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1543:46)
    at ResponseCache.get (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/Users/charlieblackstock/repos/farworld/node_modules/next/dist/server/base-server.js:1463:53)
  ```
    
here is route file
next version: 14.1
    
```
 /** @jsxImportSource frog/jsx */
import { Button, Frog } from 'frog'
import { handle } from 'frog/vercel'

const app = new Frog({
  basePath: '/api',
  // Supply a Hub API URL to enable frame verification.
  // hubApiUrl: 'https://api.hub.wevm.dev',
})

// Uncomment to use Edge Runtime
// export const runtime = 'edge'

app.frame('/', (c) => {
  const { buttonValue, status } = c
  console.log('🚀 ~ app.frame ~ buttonValue:', buttonValue)
  return c.res({
    image: (
      <div style={{ color: 'white', display: 'flex', fontSize: 60 }}>
        {status === 'initial' ? <div>Select your fruit!</div> : <div>Selected: {buttonValue}</div>}
      </div>
    ),
    intents: [
      <Button value="apple">Apple</Button>,
      <Button value="banana">Banana</Button>,
      <Button value="mango">Mango</Button>,
    ],
  })
})

export const GET = handle(app)
export const POST = handle(app)
```

**Comment by tmm** [comment] 2024-02-28 21:33
Is that the full error? When I add this frame locally, I am getting `Expected <div> to have explicit "display: flex" or "display: none" if it has more than one child node.` Fix is to either add `display` to `div`s below or remove them.

```diff
- {status === 'initial' ? <div>Select your fruit!</div> : <div>Selected: {buttonValue}</div>}
+ {status === 'initial' ? Select your fruit! : Selected: {buttonValue}}
```

**Comment by jxom** [comment] 2024-02-28 21:38
@chuckstock 

Just fixed on `create-frog@0.1.1`. Try do `bunx create-frog@latest -t next` and it should solve both issues. You may need to delete the bun cache: `rm -rf /tmp/bunx-...`

**Closed as not planned by jxom** 2024-02-28 21:38 UTC

**Comment by jxom** [comment] 2024-02-28 21:48
Also updated docs regarding @tmm's comment: https://github.com/wevm/frog/commit/5af850f61b8e4c4ba6a257b733ded60df84564ce

**Comment by chuckstock** [comment] 2024-02-28 21:50
@jxom  still getting this error on fresh project with bun create and clicking any button

STR:
1. `bunx create-frog@latest -t next`
2. `bun install`
3. visit `http://localhost:3000/api` and view dev tools
4. click any button

```
SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/dev/routes.js:160:40)
    at dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:34:33)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:11:16)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:246:39)
    at _Hono.dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:254:11)
    at _Hono.fetch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:68:25)
    at _Hono.eval (webpack-internal:///(rsc)/./node_modules/hono/dist/adapter/vercel/handler.js:7:20)
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63815
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56866
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:37102)
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54639
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:36351)
    at /Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54601
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at eU.execute (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53994)
    at eU.handle (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65073)
    at doRender (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/base-server.js:1333:60)
    at cacheEntry.responseCache.get.routeKind (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/base-server.js:1543:46)
    at ResponseCache.get (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/Users/charlieblackstock/repos/my-first-frog/node_modules/next/dist/server/base-server.js:1463:53)
    ```

**Comment by jxom** [comment] 2024-02-28 21:54
Is your bun cache cleared for `create-frog`?

**Comment by chuckstock** [comment] 2024-02-28 22:02
yeah i had to clear it to update to the latest version. it successfully made the repo and it was erroring before i cleared the cache.

**Comment by chuckstock** [comment] 2024-02-28 22:03
i've tried manually installing frog and hono into another nextjs repo and i get the same error

**Comment by jxom** [comment] 2024-02-28 22:08
Hmm, I can't seem to repro on next project here: https://github.com/jxom/frog-next-repro

Can you share yours?

**Comment by chuckstock** [comment] 2024-02-28 22:15
hmm interesting, i just cloned that repo (https://github.com/jxom/frog-next-repro) and got the same issue. Let me debug my local environment, before i waste anymore of your time.

**Comment by chuckstock** [comment] 2024-02-28 22:19
@jxom i just had a co-worker clone and install https://github.com/jxom/frog-next-repro this repo and he's getting the same error as me.

**Comment by jxom** [comment] 2024-02-28 22:23
Hmm weird. Same with `pnpm`?

**Comment by jxom** [comment] 2024-02-28 22:25
Could try `bun pm cache rm` also to clear bun module cache?

**Comment by chuckstock** [comment] 2024-02-28 22:36
tried with`pnpm` and cleared bun cache and tried again with same result. i'm on node `v18.19.0` if you think that matters

**Comment by jxom** [comment] 2024-02-28 22:45
Hmm weird. Still can't reproduce on node 18. @tmm tried to repro too, but couldn't.

**Comment by chuckstock** [comment] 2024-02-28 22:48
yeah bumped node to 20 and getting this error now:

```
SyntaxError: Unexpected non-whitespace character after JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/frog/_lib/dev/routes.js:160:40)
    at dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:34:33)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:11:16)
    at eval (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:246:39)
    at _Hono.dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:254:11)
    at _Hono.fetch (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:68:25)
    at _Hono.eval (webpack-internal:///(rsc)/./node_modules/hono/dist/adapter/vercel/handler.js:7:20)

```

**Comment by chuckstock** [comment] 2024-02-28 22:55
@jxom oh wow i found it. We have conflicting cookie names. we use a cookie called session for our auth, and i found that frog uses a cookie called `session`

i think frog, should have name-spaced cookies to avoid conflicts like these

when i deleted my session cookie frog works

**Comment by jxom** [comment] 2024-02-28 22:56
lol rip 💀 we can take a look into it
