### ISSUE TITLE
When using Bun, consuming c.req.json() throws an error

### ISSUE THREAD

**Issue by m4nuC** [wevm/frog-archived#122] opened 2024-03-08 21:34 UTC
### Describe the bug

Using await c.req.json()  in any route will yield the following error.

![image](https://github.com/wevm/frog/assets/1518868/0a22bc3f-e2de-431d-bb20-6d8671b48206)

Possibly related to this issue: https://github.com/wevm/frog/issues/120

### Frog Version

0.5.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment] 2024-03-11 11:10
Hey @m4nuC, it would be awesome if you would provide a link to reproducible example!
Are you experiencing such when it's request has a `GET` method present or not?

Initially, Farcaster Bot makes a `GET` request, which doesn't have a body defined, therefore reading it might cause some issues.

After the initial render, on button clicks `POST` requests are being made that have a body defined.

Since there are no steps to reproduce, I would advocate trying to read `c.req.json()` when `c.req.method === 'GET'` is present.

Also, take the notice that raw `Request` body normally can be read only once, and reading it multiple times would throw an error, but Hono caches the read result so it won't throw an error.
https://developer.mozilla.org/en-US/docs/Web/API/Request
https://github.com/honojs/hono/blob/4ca5f60def726731b3afbf3f6137f0a4b92d8b27/src/request.ts#L222-L224

**Comment by tmm** [comment] 2024-03-11 15:29
Closing until we get a minimal reproduction.

**Closed as not planned by tmm** 2024-03-11 15:29 UTC
