### ISSUE TITLE
Property 'title' is missing when using templates

### ISSUE THREAD

**Issue by MattWong-ca** [wevm/frog-archived#485] opened 2024-09-10 01:29 UTC
### Describe the bug

When I run `npm init frog` to start a new project, I tried using the default or next templates but I get the `Property 'title' is missing` error. 

I checked the codebase and [this commit](https://github.com/wevm/frog/commit/ab1a969659f3d9d170f2f463ab6e51a286f3973f) seems to fix it, but I don't see the `title: 'Frog Frame',` line when I initialize a new project.

### Steps To Reproduce

1. Run `npm init frog`
2. Choose default template
3. Check the Frog initialization, the default title isn't there

### Frog Version

0.17.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment] 2024-09-10 03:38
PR welcome :)

**Comment by dalechyn** [comment] 2024-09-10 10:57
Hi! This issue was fixed in https://github.com/wevm/frog/pull/425 and the fix rolled out at [`create-frog@0.1.8`](https://github.com/wevm/frog/releases/tag/create-frog%400.1.8).

It might be that you have a cached `create-frog` package locally?

I tried reproducing it and unfortunately cannot reproduce.
Also to double check, you can check the `templates` folder on npm directly and see that `title` is set in all of the templates: https://www.npmjs.com/package/create-frog?activeTab=code.

Feel free to comment with your findings.

**Closed as not planned by dalechyn** 2024-09-10 10:57 UTC
