### ISSUE TITLE
400 Error when using Text Inputs with latest frog

### ISSUE THREAD

**Issue by thebreadcat** [wevm/frog-archived#441] opened 2024-07-25 18:40 UTC
### Describe the bug

A lot of folks on Discord have been reporting this issue in various forms for a bit now.   When downloading the latest frog and using create frog for next.js and deploying to vercel for hosting (with no code changes besides adding a title to the app config to get it to run) the frame fails with a 400 in the Warpcast Validator.  

``validateFrameEmbed 400 - Missing image URL``

### Link to Minimal Reproducible Example

https://frog-input-test-thebreadcat-thebreadcats-projects.vercel.app/api

### Steps To Reproduce

Install Frog using the create frog command for next.js from the docs.
Deploy to Vercel `vercel`
Test URL in Warpcast Frame Validator tools: https://warpcast.com/~/developers/frames
Get a 400 error.

Remove the Text Area and redploy to vercel
See Frame without 400 error.

### Frog Version

0.15.2

### TypeScript Version

5.5.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

Note: I did see another version of this bug get reported but self-closed without any additional info so I DID check...but it was closed and I think this issue has a lot of people stopped from getting things built with Frog currently.

**Comment by dalechyn** [comment] 2024-07-25 18:57
Can you also add a link to the actual reproducible example source code?

**Comment by thebreadcat** [comment] 2024-07-25 19:06
it's the code from the install.  I can push that code up to github but it's 99.9% unchanged from running "npm init frog -- -t next" let me know if you'd still like me to push it up.   (Thanks in advance for looking into this)

**Comment by XhrCkYsSgZokJL** [comment] 2024-07-26 21:16
"Reset" type and "TextInput" type buttons both not working on latest for us.

**Comment by dalechyn** [comment] 2024-07-26 21:46
Should have been fixed by #447. Can't reproduce rn.

@XhrCkYsSgZokJL, please create a separate issue with a min. repro to take a look at.

**Closed as completed by dalechyn** 2024-07-26 21:46 UTC
